export class ErrorCode {
    static INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    static GRAPHQL_PARSE_FAILED = "GRAPHQL_PARSE_FAILED";
    static GRAPHQL_VALIDATION_FAILED = "GRAPHQL_VALIDATION_FAILED";
    static BAD_USER_INPUT = "BAD_USER_INPUT";
    static BAD_REQUEST = "BAD_REQUEST";
    static ID_NOT_FOUND = "ID_NOT_FOUND";
    static VIOLATION_CONSTRAINT = "DUPLICATE_DATA";
}